name: flutter_sweet_alert
description: sweet alert for flutter.
version: 0.0.1
homepage: https://github.com/OscarTinajero117/flutter_sweet_alert

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sequence_animation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
